tidymodels/infer

- cran-comments.md
- tests/testthat/test-specify.R
Saw 'help wanted' to write test_that.
Added two very simple tests to test-specify.R, which I tied to issue #142 .
Not sure useful at all.   Was hoping to eliminate `assertive::assert_is_data.frame(x)` in specify.R
Found your code very succinct.   Packages like "methods::" that take me a while to work through.
Upshot:   if you can give me a bit of direction I'd like to see if I can be useful to writing tests.
No hard feelings if not.   
Thx.
jim
> 142 branch

- _pkgdown.yml
@andrewpbray I forgot to remove the okcupiddata vignettes from the pkgdown build so the links at infer.netlify.com are broken. This should remove it on the travis build to gh-pages.
> Remove DEV vignettes

- DESCRIPTION
- NEWS.md
- R/calculate.R
- R/conf_int.R
- R/p_value.R
- R/rep_sample_n.R
- R/specify.R
- R/utils.R
- R/visualize.R
- tests/testthat/test-utils.R
This is a PR to close issue #149. Few notes:
- No tests seem to be newly broken. One test is failing (for `chisq_stat()` and `chisq_test` relations) but so it does in current `develop` branch (commit 9af42a7f).
- It deals purely with implementation methods without changing assertion logic. It introduces `check_type()` function for custom type checks by supplying predicate function and expected type name (not always necessary).
- A slight improvement can be made in `check_type()` by using `rlang::as_function()` to allow predicate function to be in form of anonymous "formula-function". This might be handy in case of complicated checks (for example [here](https://github.com/andrewpbray/infer/blob/ee1b621523c47303ecbd0a059f7ed1705b8cd9b0/R/conf_int.R#L51)). However, I think encapsulating …
> Stop using package {assertive} in favor of custom type checks (#149)

- NEWS.md
- R/calculate.R
- R/conf_int.R
- R/generate.R
- R/hypothesize.R
- R/p_value.R
- R/print_methods.R
- R/rep_sample_n.R
- R/set_params.R
- R/specify.R
- R/utils.R
- R/visualize.R
- R/wrappers.R
- tests/testthat/test-utils.R
- tests/testthat/test-visualize.R
This is a PR for issue #155.
I ended up replacing all `stop()`, `warning()`, and `message()` with `stop_glue()`, `warning_glue()`, and `message_glue()` in which:
- `call. = FALSE` is default. This goes well with [tidyverse style guide](http://style.tidyverse.org/error-messages.html#problem-statement) and might be considered as part of #102.
- If supplied object evaluates in `NULL` it is printed as 'NULL' (as discussed in issue). Separate wrapper `glue_null()` for `glue::glue()` is implemented for this.
Also `glue_null()` is used instead of `paste()` and `paste0()`.
**Note** that current version of `print.infer()` has slightly different behavior in case input hasn't any of desired three attributes: it prints empty line before printing tibble. This can happen only if `infer` object wasn't …
> Fully use glue package (#155)

- NEWS.md
- R/calculate.R
- tests/testthat/test-calculate.R
The reason was that `table()` inside of `calc_impl.Chisq()` computes values in alphabetical order of input levels. If proportion are supplied in that order, everything was fine. Fixed with reordering the output of that `table()`.
> Fix `calculate()` to not depend on order of `p` (fixes #122).

- NEWS.md
- R/calculate.R
- R/utils.R
- man/calculate.Rd
- tests/testthat/test-calculate.R
This is a PR following a conversation in #50.
Adding new options to `calculate()` isn't straightforward as I hoped: they still should be carefully added to different types of checks. During that I treated `"sum"` as `"mean"` (without possibility of hypothesising about point value) and `"count"` as `"prop"` (again without point hypothesis).
> Add new options for `calculate()` (issue #50)

- R/specify.R
- tests/testthat/test-specify.R
> More verbose error message for argument checks in `specify()`

- vignettes/chisq_test.Rmd
- vignettes/flights_examples.Rmd
- vignettes/two_sample_t.Rmd
Avoids a tiny bit of redundancy in code examples. Cleaner PR than #200.
> Use pull() only (without select()) in vignettes

- DESCRIPTION
- R/calculate.R
- R/generate.R
- R/hypothesize.R
- R/specify.R
- R/utils.R
- tests/testthat/test-generate.R
- tests/testthat/test-hypothesize.R
- tests/testthat/test-utils.R
> Manage "infer" class more systematically

- R/calculate.R
- R/wrappers.R
This suppresses the warnings originating from `chisq.test()` in two spots where the function is only used to calculate a test statistic.
> Suppress chisq warnings

- .travis.yml
- tests/testthat.R
This PR contains updates that enable use of {vdiffr} tests on Travis. The main reason why they didn't work was related to change of default random generation algorithm in 3.6.0 version. Command `RNGversion("3.5.0")` in 'tests/testthat.R' file somehow didn't affect the `vdiffr::manage_cases()` and `devtools::test()` functions, thus generating reference plots based on 3.6.0 random generation algorithm. However, R CMD CHECK respected that command and generated plots based on 3.5.0 version.
To enable use of {vdiffr} on Travis, I removed usage of 3.5.0 version from 'tests/testthat.R' and disabled {vdiffr} tests only on old R version. With this setup Travis actually performs {vdiffr} checks, see https://travis-ci.org/tidymodels/infer/builds/594139024.
cc @andrewpbray, @ismayc
> Restart use of vdiffr on Travis

- R/shade_confidence_interval.R
- R/shade_p_value.R
- R/utils.R
- tests/figs/shade-confidence-interval/ci-extra-aes-1.svg
- tests/figs/shade-confidence-interval/ci-extra-aes-2.svg
- tests/figs/shade-p-value/pval-extra-aes-1.svg
- tests/figs/shade-p-value/pval-extra-aes-2.svg
- tests/figs/shade-p-value/pval-extra-aes-3.svg
- tests/testthat/test-shade_confidence_interval.R
- tests/testthat/test-shade_p_value.R
This PR updates `shade_confidence_interval()` and `shade_p_value()` to properly use `...` for extra aesthetic adjustments.
Closes #259.
> Make `shade_*()` functions use `...`

- R/set_params.R
- R/specify.R
- tests/testthat/test-specify.R
This PR:
- Fixes #256.
- Adds check for response and explanatory variables to be symbolic and not character (so that `specify(mtcars, response = "mpg")` throws informative error).
> Refactor `set_params()` and `parse_variables()`

- R/calculate.R
- man/chisq_stat.Rd
- man/chisq_test.Rd
- tests/testthat/test-calculate.R
- vignettes/observed_stat_examples.Rmd
- vignettes/t_test.Rmd
Some minor adjustments to `calculate()` to address #232--I'll comment some more explanation on that thread in a second, but the grammar for calculating one-sample t-test statistics should align with the grammar of the package a bit more clearly now. No breaking changes. I've also updated testing coverage and vignettes to reflect the change.
Also, in making adjustments re: @ismayc's comments on my last PR, I forgot to run `devtools::document()` on the updated files. The first commit (#
43859de) contains the updated docs.
> make hypothesizing null in t-tests more expressive (#232)

- R/visualize.R
- man/visualize.Rd
- vignettes/anova.Rmd
- vignettes/chi_squared.Rmd
- vignettes/infer.Rmd
- vignettes/observed_stat_examples.Rmd
- vignettes/t_test.Rmd
Hi there!🐳
A few commits to address @AmeliaMN 's issue #278 about adding more explanation on how to use theoretical methods in the package. I've added a section to the `infer` vignette about theoretical methods, mentioned theoretical alternatives to the randomization-based approaches in each of the other vignettes, and included some examples of visualizing the theoretical null distribution in the `visualize()` help-file. 
From my understanding, {infer}'s functionality for theoretical methods is limited to visualization—I'm not sure that p-values using the theoretical null distribution are supported. Let me know if I'm missing some functionality here, though!
> more documentation for theoretical methods (closes #278)

- R/shade_confidence_interval.R
- R/shade_p_value.R
- R/utils.R
- tests/testthat/test-shade_confidence_interval.R
- tests/testthat/test-shade_p_value.R
Hi all!
A PR to address an error message that often tripped students up last semester—when piping after visualize, 
``` r
library(infer)
gss %>% 
specify(response = hours)  %>% 
hypothesize(null = "point", mu = 40) %>% 
generate(reps = 100, type = "bootstrap") %>% 
calculate(stat = "mean") %>%
visualize() %>%
shade_p_value(obs_stat = 1, direction = "both")
#> Warning: Removed 1244 rows containing missing values.
#> Error: `color` must be 'color string', not 'list'.
```
<sup>Created on 2020-01-16 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
Before running the current argument checking messages, `shade_p_value` and `shade_confidence_interval` will now check if a plot object was supplied as an argument, and raise an error if so. The new error for the code above would …
> add error for piping after visualize()

- NEWS.md
- R/calculate.R
- R/infer.R
- R/utils.R
- man/calculate.Rd
- tests/testthat/test-calculate.R
- vignettes/observed_stat_examples.Rmd
Hi there!
This pull request adds `stat = "ratio of props"` and `stat = "odds ratio"` as options to `calculate` in response to issue #285. I've added unit testing and documentation (in `observed_stat_examples.Rmd`) for both of them as well!
I believe I've covered all bases in `.implement_new_methods.md`, but let me know if I'm missing any functionality for these two stats.
> implement stat = "ratio of props" and "odds ratio" (#285)

- NEWS.md
- R/calculate.R
- tests/testthat/test-calculate.R
Some small changes to address the build failures resulting from breaking changes in the version of `dplyr` to be submitted to CRAN in the next couple weeks.
From the `dplyr` [release notes](https://github.com/tidyverse/dplyr/blob/master/NEWS.md): 
* “n() and row_number() can no longer be called directly when dplyr is not loaded,” hence the transition of an `n()` to `dplyr::n()` in `calculate`.
* “expect_equal() uses all.equal() internally.” I’ve transitioned a few `expect_equal`s to `expect_equivalent`s in unit tests so that dataframes with matching entries will pass even if `infer` appended attributes are present in one dataframe but not in another.
If this looks good, once this is merged, I'll start prepping for CRAN release!
> address dplyr 1.0.0 breaking changes

- NEWS.md
- R/generate.R
- tests/testthat/test-generate.R
> Deal with `generate()` in case of "simulate" and 'x' response

- NEWS.md
- R/wrappers.R
- tests/testthat/test-visualize.R
- tests/testthat/test-wrappers.R
This PR fixes #310—the `t_test()` and `t_stat()` wrappers were ignoring the `order` argument. I’ve just dropped in calls to the same `reorder_explanatory()` from `calc_impl.t()` into the `t_test()` and `t_stat()` definitions, and added unit testing to now check to make sure the two are sensitive to the `order` argument from here on out!
``` r
library(infer)
iris %>%
dplyr::filter(Species != "virginica") %>%
t_test(Petal.Length ~ Species, order = c("setosa", "versicolor"))
#> # A tibble: 1 x 6
#>   statistic  t_df  p_value alternative lower_ci upper_ci
#>       <dbl> <dbl>    <dbl> <chr>          <dbl>    <dbl>
#> 1     -39.5  62.1 9.93e-46 two.sided      -2.94    -2.66
iris %>%
dplyr::filter(Species != "virginica") %>%
t_test(Petal.Length ~ Species, order = c("versicolor", "setosa"))
#> # …
```
> fix order arg in t wrappers

- .github/workflows/pkgdown.yaml
- _pkgdown.yml
- docs/CNAME
infer's CNAME entry is now set up with RStudio! This commit, if merged to `master`, should set up build commands to send a tidymodels-style pkgdown site to infer.tidymodels.org. This will likely break updates to the existing site, but we can temporarily restore the old website while we get the new one up and running, and then set up automatic redirects from the old site to this one easily through the Netlify UI. (This setup is what we used to get [stacks.tidymodels.org](https://stacks.tidymodels.org) up and running.. there might be some differences in the setup for new sites vs packages with previously existing ones.)
Once this is merged…
* restore [infer.netlify.com](https://infer.netlify.com) to host the build from the previous commit through the Netlify UI
* wait… the CNAME will take …
> launch infer.tidymodels.org

- R/utils.R
To change `Error: Statistic is based on a difference or ratio; the explanatory variableshould have two levels.` to `Error: Statistic is based on a difference or ratio; the explanatory variable should have two levels.`
> Error msg tweak

- vignettes/infer.Rmd
This PR fixes a minor typo in the vignette "Getting to Know Infer" by switching the order of comments that accompany examples of declaring response and explanatory variables with `specify()` using either formula syntax or named arguments.
> switch order of code comments in package vignette

- NEWS.md
- R/infer.R
- R/wrappers.R
- man/chisq_stat.Rd
- man/chisq_test.Rd
- man/prop_test.Rd
- man/t_test.Rd
- tests/testthat/test-wrappers.R
This PR adds a `success` argument to `prop_test()` and closes #343. (More discussion there!)
Also clarifies documentation on >2-sample tests related to arguments being ignored. This was being done already, though the `alternative` column was supplied in output in the >2-sample case (when it is ignored by `stats::prop.test`).
> add success argument to prop_test

- tests/testthat/helper-data.R
- tests/testthat/test-shade_confidence_interval.R
- tests/testthat/test-shade_p_value.R
- tests/testthat/test-visualize.R
From BDR to the `vdiffr` maintainers a few weeks ago:
```
...
> Suggested packages should be used conditionally: see §1.1.3.1 of
> 'Writing R Extensions'.  Some of the requirements of vdiffr are hard to
> install on a platform without X11 such as M1 Macs: see the logs at
> https://www.stats.ox.ac.uk/pub/bdr/M1mac/.
>
> In some cases there are other suggested packages not used conditionally:
> you can check all of them by setting environment variable
> _R_CHECK_DEPENDS_ONLY_=true  -- see
> https://cran.r-project.org/doc/manuals/r-devel/R-ints.html#Tools .
>
> Please correct ASAP and before 2021-01-12 to safely retain the package
> on CRAN.
```
From the `vdiffr` maintainers:
```
Hi everyone,
A simple way to make vdiffr usage conditional is to define your own
`expect_doppelganger()` as …
```
> use vdiffr conditionally

- NEWS.md
- R/calculate.R
- R/hypothesize.R
- tests/testthat/test-calculate.R
- vignettes/observed_stat_examples.Rmd
In working through #347, I realized that we had yet to implement a standardized proportion z statistic for one categorical variable. 
It seems like there was previously an implementation that was no longer dispatched to, returning `x` itself instead of the statistic. (I think we should raise a similar warning to the one that's [currently commented out](https://github.com/tidymodels/infer/blob/eaf93a4fbf8647c081f3677fa3b64b824e64951e/R/calculate.R#L97-L101) in those situations. Glad to put in a PR there if others are on board.) I just resituated the implementation, updating its references to the internals of the `x` object and making sure `hypothesize()` brings along the appropriate attributes.
🐏
> Implement the standardized proportion z statistic for one categorical variable

- NEWS.md
- R/rep_sample_n.R
- man/rep_sample_n.Rd
- tests/testthat/test-rep_sample_n.R
Much better!☃️
This PR adds a `prop` argument to `rep_slice_sample()` as an alternative to the `n`  argument for specifying the proportion of rows in the supplied data to sample per replicate and simplifies the `rep_sample_n` and `rep_slice_sample` internals significantly.
Continuing discussion from #362, making use of `dplyr::slice_sample()` more straightforwardly, I'm not sure we need to wrap `dplyr::sample_n` and `dplyr::slice_sample` separately. This implementation makes `rep_sample_n` a wrapper around `rep_slice_sample` that ignores the `prop` argument, and otherwise doesn't need to introduce any more complexity to handle arguments appropriately.
The `missing_n` argument in `process_slice_n` allows the user to pass the `prop` argument while leaving the default `n = 1` in …
> refactor, implement prop argument in `rep_slice_sample()`

- NEWS.md
- R/calculate.R
- tests/testthat/test-calculate.R
#370 was due to to the fact that dplyr evaluates `attr(x, "params")` in reference to the column `x` in `.data` rather than the `x` in `calc_impl.t`'s environment. This came up inside of `calc_impl.t`, though I checked for similar usages in other `calc_impl` methods and couldn't find any. This fixes the issue, adds a small test, and updates NEWS.🦥
Closes #370.
> fix calculate error when columns are named `x`

- NEWS.md
- R/set_params.R
Closes #374. :-) 
``` r
library(tidyverse)
library(infer)
data(gss)
gss_rd <- gss %>%  filter(partyid %in% c("rep", "dem"))
class(gss_rd$partyid)
#> [1] "factor"
gss_null<-gss_rd %>% specify(college ~ partyid, success = "degree") %>%
hypothesize(null = "independence") %>% 
generate(reps = 1000, type = "permute") %>% 
calculate(stat = "diff in props", order = c("rep", "dem")) 
gss_stat <- gss_rd %>% specify(college ~ partyid, success = "degree") %>%
calculate(stat = "diff in props", order = c("rep", "dem")) 
gss_null %>% visualise()+shade_p_value(obs_stat = gss_stat, direction = "both")
```
``` r
gss_rd <- gss %>%  filter(partyid %in% c("rep", "dem")) %>% mutate(partyid = as.character(partyid) )
class(gss_rd$partyid)
#> [1] "character"
gss_null<-gss_rd %>% specify(college ~ partyid, …
```
> correct `theory_type` on `stat = "diff in props"` w factor

- NEWS.md
- R/set_params.R
- tests/testthat/test-specify.R
Switches from `length(levels())` to `length(unique())` when determining the number of levels in factors and messages on dropped factor levels!
``` r
library(infer)
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
gss %>%  
filter(partyid %in% c("rep", "dem")) %>%
specify(age ~ partyid) %>%
calculate(stat = "t", order = c("dem", "rep"))
#> Dropping unused factor levels c("ind", "other", "DK") from the supplied explanatory variable 'partyid'.
#> # A tibble: 1 x 1
#>    stat
#>   <dbl>
#> 1 0.782
```
<sup>Created on 2021-04-14 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0.9001)</sup>
Closes …
> improve handling of unused factor levels

- .github/workflows/check-standard.yaml
Been seeing:
```
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
unable to load shared object '/Users/runner/work/_temp/Library/digest/libs/digest.so':
dlopen(/Users/runner/work/_temp/Library/digest/libs/digest.so, 6): Library not loaded: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libR.dylib
Referenced from: /Users/runner/work/_temp/Library/digest/libs/digest.so
Reason: image not found
Calls: loadNamespace ... asNamespace -> loadNamespace -> library.dynam -> dyn.load
```
on the macOS GHA builds for a bit now. This PR workshops our package installation in hopes to get that `digest` dependency squared away. :-)
> Fix macOS build on GHA

- README.Rmd
- README.md
Closes #385. `fig.cap = " "` prevents the alt text from being copied to the `<img>` title.
> add alt text to README figures

- vignettes/infer.Rmd
- vignettes/observed_stat_examples.Rmd
Some vignette updates following up on #391!
The dropped warning in the `infer.Rmd` vignette is due to an update to the `gss` data that dropped rows without complete cases a release or two ago.
> add `fit()` functionality to vignettes

- R/fit.R
- man/fit.infer.Rd
- tests/testthat/test-fit.R
This PR introduces (explicit) support for logistic regression in `fit.infer` via the `mode` argument! Previously, we had supported logistic regression already if a `family` argument was passed via `...`, but this implements a more tidymodels-esque and well-documented interface.
A quick reprex of the interface:
``` r
library(infer)
gss %>%
specify(hours ~ age + college) %>%
fit()
#> # A tibble: 3 x 2
#>   term          estimate
#>   <chr>            <dbl>
#> 1 intercept     40.6    
#> 2 age            0.00596
#> 3 collegedegree  1.53
gss %>%
specify(college ~ age + hours) %>%
fit(mode = "classification")
#> # A tibble: 3 x 2
#>   term      estimate
#>   <chr>        <dbl>
#> 1 intercept -1.13   
#> 2 age        0.00527
#> 3 hours      0.00698
```
On the backend, `mode` just handles the …
> implement logistic regression in `fit.infer`

- R/generate.R
- man/generate.Rd
Clarify that generate can come after `specify()` alone (CIs) or `specify()` and then `hypothesize()` (HTs).
Closes #402.
> Clarify generate description

- R/get_confidence_interval.R
- R/shade_p_value.R
- README.Rmd
- README.md
- man/get_confidence_interval.Rd
- man/shade_p_value.Rd
- tests/testthat/test-get_confidence_interval.R
- vignettes/anova.Rmd
- vignettes/chi_squared.Rmd
- vignettes/observed_stat_examples.Rmd
- vignettes/t_test.Rmd
Closes #406.
Some of the more substantive search + replaces:
* `*_distr` -> `*_dist`
* `*_distn` -> `*_dist`
* `*_simulated` -> `*_sim`
* `*_theoretical` -> `*_theor`
* `boot `-> `boot_dist`
* `*distribution*` -> `*dist*`
One thing I'm still unsure on: what should we call a set (distribution?) of models fitted following permutation? These are currently called `null_fits` and referred to as distributions.
This PR leaves `docs/` alone—will regenerate during release prep!
> standardize distribution naming

- .Rbuildignore
- DESCRIPTION
- LICENSE
- LICENSE.md
Hi all,
This PR would re-license {infer} to use the MIT license to bring the package's licensing in line with other packages in the tidymodels, conform to a license approved by the Journal of Open Source Software, and make the package license as clear and permissive as possible. To do so, we need the approval of all copyright holders. I've tagged those listed as a [contributor](https://github.com/tidymodels/infer/graphs/contributors) of significant changes via GitHub's contributor graphs.
@andrewpbray, @ismayc, @echasnovski, @beanumber, @mine-cetinkaya-rundel, @rudeboybert, @richierocks, @jayleetx, @nicksolomon, @PirateGrunt, @jimrothstein would you permit re-licensing infer from CC0 to the MIT license? If so, please comment "I agree" below.
Much appreciated!
> re-license to MIT

- NEWS.md
- R/generate.R
- man/generate.Rd
Specifies that only testing on one proportion is supported in the `type = "draw"` option and adds an example to the `generate` docs. Also, makes a small update to `NEWS` for this and the last PR.
Closes #415.
> clarify docs re: `type = "draw"`

- .Rbuildignore
- R/calculate.R
- R/fit.R
- R/generate.R
- man-roxygen/seeds.Rmd
- man/calculate.Rd
- man/fit.infer.Rd
- man/generate.Rd
- vignettes/infer.Rmd
This PR adds a section to the docs for `generate` and functions used after `generate()`ing about reproducibility when resampling! Notes that infer respects the state of the RNG and provides an example of how to reproduce exact results.
Worth mentioning that this PR doesn't introduce a more integrated solution to setting the RNG seed, as @kellieotto suggested in #416. I think this avoids introducing an additional layer of abstraction for RNGs (which I find tricky, personally?), though am open to discuss further if folks feel this might be worthwhile.
Closes #416.
> improve docs re: `set.seed` and reproducibility

- inst/CITATION
Our submission to JOSS was accepted!🎊 https://joss.theoj.org/papers/10.21105/joss.03661#
This PR adds the JOSS citation to the CITATION file. I just worked from `devtools::use_citation()` and pattern-matching [the tidyverse's entry](https://github.com/tidyverse/tidyverse/blob/master/inst/CITATION) to fill in the citation info from JOSS. The output looks like this:
```
> citation("infer")
Couch et al., (2021). infer: An R package for tidyverse-friendly statistical
inference. Journal of Open Source Software, 6(65), 3661,
https://doi.org/10.21105/joss.03661
A BibTeX entry for LaTeX users is
@Article{,
title = {{infer}: An {R} package for tidyverse-friendly statistical inference},
author = {Simon P. Couch and Andrew P. Bray and Chester Ismay and Evgeni Chasnovski and Benjamin S. Baumer and …
```
> add CITATION file

- .github/workflows/check-standard.yaml
- .github/workflows/pkgdown.yaml
- DESCRIPTION
- README.Rmd
- README.md
> Move to "main"

- DESCRIPTION
- NEWS.md
- R/infer.R
- R/specify.R
- R/utils.R
- R/wrappers.R
- tests/testthat/test-wrappers.R
Closes #436. [EDIT: corrected linked issue.]
This PR switches out ad-hoc standardization of variables types with a `standardize_variable_types` utility that, for the most part, does what the ad-hoc standardization did previously, but also enables `specify` and wrappers to handle ordered factors.
> unify standardization of variable types

- DESCRIPTION
addresses recent check NOTEs:
```
❯ checking dependencies in R code ... NOTE
Namespace in Imports field not imported from: ‘tidyselect’
All declared Imports should be used.
❯ checking Rd cross-references ... NOTE
Package unavailable to check Rd xrefs: ‘parsnip’
```
> clarify dependencies

- DESCRIPTION
- R/generate.R
- R/shade_confidence_interval.R
- R/shade_p_value.R
- R/visualize.R
- tests/testthat.R
- tests/testthat/helper-data.R
- tests/testthat/test-aliases.R
- tests/testthat/test-assume.R
- tests/testthat/test-calculate.R
- tests/testthat/test-fit.R
- tests/testthat/test-generate.R
- tests/testthat/test-get_confidence_interval.R
- tests/testthat/test-get_p_value.R
- tests/testthat/test-hypothesize.R
- tests/testthat/test-observe.R
- tests/testthat/test-print.R
- tests/testthat/test-rep_sample_n.R
- tests/testthat/test-shade_confidence_interval.R
- tests/testthat/test-shade_p_value.R
- tests/testthat/test-specify.R
- tests/testthat/test-utils.R
- tests/testthat/test-visualize.R
- tests/testthat/test-wrappers.R
Closes #475, closes #477, closes #478!
> transition to testthat 3e

- NEWS.md
- R/generate.R
- R/rep_sample_n.R
- man/rep_sample_n.Rd
- tests/testthat/test-rep_sample_n.R
Closes #480.🍄
With this PR:
``` r
library(infer)
library(tibble)
df <- tibble(
id = 1:5,
letter = factor(c("a", "b", "c", "d", "e")),
wts = c(.5, .4, .3, .2, .1)
)
set.seed(1)
rep_slice_sample(df, n = 2, reps = 5, weight_by = c(.5, .4, .3, .2, .1))
#> # A tibble: 10 × 4
#> # Groups:   replicate [5]
#>    replicate    id letter   wts
#>        <int> <int> <fct>  <dbl>
#>  1         1     1 a        0.5
#>  2         1     2 b        0.4
#>  3         2     2 b        0.4
#>  4         2     4 d        0.2
#>  5         3     1 a        0.5
#>  6         3     4 d        0.2
#>  7         4     5 e        0.1
#>  8         4     3 c        0.3
#>  9         5     3 c        0.3
#> 10         5     1 a        0.5
set.seed(1)
rep_slice_sample(df, n = 2, reps = 5, weight_by = df$wts)
#> # A …
```
> allow unquoted column name for `weight_by` in `rep_slice_sample()`

- R/generate.R
As of now, the package re-computes `format_params(x)` in each replicate, which accounts for about half of the total evaluation time of the function.
With `main` dev:
``` r
library(infer)
gss_hyp <-
gss %>%
specify(response = sex, success = "female") %>%
hypothesize(null = "point", p = .5)
bench::mark(
generate = generate(gss_hyp, reps = 1000, type = "draw")
)
#> # A tibble: 1 × 6
#>   expression      min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr> <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 generate     58.4ms   61.7ms      15.2    42.5MB     30.4
```
With this PR:
``` r
#> # A tibble: 1 × 6
#>   expression      min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr> <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 generate     33.5ms   33.5ms      29.9    40.5MB …
```
> speed up `generate(type = "draw")`

- NEWS.md
- R/get_confidence_interval.R
- tests/testthat/_snaps/get_confidence_interval.md
- tests/testthat/test-get_confidence_interval.R
Closes #520. :)
With this PR:
``` r
library(infer)
data <- data.frame(
prop = seq(0, 1, length.out = 10),
group = rep(c("a", "b"), each = 5L)
)
set.seed(1)
boot_dist <-
data %>%
specify(prop ~ group) %>%
hypothesize(null = "independence") %>%
generate(reps = 1000, type = "bootstrap") %>%
calculate(stat = "diff in medians", order = c("b", "a"))
get_confidence_interval(boot_dist, .95)
#> Warning: 4 estimates were missing and were removed when 
#> calculating the confidence interval.
#> # A tibble: 1 × 2
#>   lower_ci upper_ci
#>      <dbl>    <dbl>
#> 1    0.278    0.889
```
<sup>Created on 2023-12-22 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
> handle missing values when calculating confidence intervals

- DESCRIPTION
- NEWS.md
- README.Rmd
- README.md
- cran-comments.md
> infer 1.0.7 release candidate

- tests/testthat/_snaps/visualize/viz-fit-bare.svg
- tests/testthat/_snaps/visualize/viz-fit-conf-int.svg
- tests/testthat/_snaps/visualize/viz-fit-no-h0.svg
- tests/testthat/_snaps/visualize/viz-fit-p-val-both.svg
- tests/testthat/_snaps/visualize/viz-fit-p-val-left.svg
- tests/testthat/_snaps/visualize/viz-fit-p-val-right.svg
- tests/testthat/test-visualize.R
Seeing snap failures for `visualize()` on `fit.infer()` output (first seen in #544 but can also observe on `main`)—only tests on output from `fit()`, and _all_ of the output from `fit()`. No changes to vdiffr or the graphics engine that would explain the new failures, and only on macOS, so I'm a bit confused as to what the root cause may be, but the snaps are visually indistinguishable to me.
I'm guessing macOS will pass but other check systems will fail, in which case we'll need to make snap variants depending on OS.
> address `fit.infer()` + `visualize()` snap failures

- NEWS.md
- R/print_methods.R
- tests/testthat/_snaps/print.md
- tests/testthat/test-print.R
Closes #543. Takes the tibble-esque approach of just truncating the variable descriptions and then ending with ellipses rather than "wrapping" the whole description to the console width, though I'm game to do the latter if we feel that's a better approach.
> truncate variable descriptions that are wider than the console

- DESCRIPTION
- R/visualize.R
ggplot2 3.5.2 just now made it to CRAN—may take a day or two for the runners to have the newest version.
> transition from deprecated ggplot2 function
