README.Rmd, README.md
To avoid potential problems down the road of those stinkin' curly quotes.
=> Fix formatting of quotation marks

R/calculate.R, R/generate.R, R/hypothesize.R
I had planned to have such an example in my course, so this PR adds that functionality.
Additionally, I replaced the method for checking for only one parameter being provided in the hypothesize function (there was a note there about doing it a different way).
=> Add functionality for CI and HT for standard deviation

R/calculate.R, vignettes/flights_examples.Rmd, vignettes/mtcars_examples.Rmd
Add order parameter for stat = "diff in ..." and associated test to go with it
=> order parameter

DESCRIPTION, R/hypothesize.R, docs/articles/mtcars_examples.html, docs/reference/generate.html, docs/reference/hypothesize.html, docs/reference/specify.html, man/generate.Rd, man/hypothesize.Rd, man/specify.Rd
Fixing @rudeboybert's issue [here](https://github.com/andrewpbray/infer/issues/64)
=> Import `assertive`

.travis.yml
I had to do this recently and I think the problem is that the `devtools` version is wrong on r-devel, but I think this will fix it.
=> I think this will fix r-devel

R/calculate.R
This splits the calculate function into smaller pieces for easier extension and testing. Each stat now has a corresponding implementation function. At the moment these are package-protected.
=> WIP Refactor calculate into smaller functions

NEWS.md, R/generate.R, R/specify.R, tests/testthat/test-generate.R, tests/testthat/test-specify.R
=> Account for `NULL` values

R/calculate.R, R/conf_int.R, R/generate.R, R/hypothesize.R, R/infer.R, R/p_value.R, R/print_methods.R, R/rep_sample_n.R, R/set_params.R, R/specify.R, R/utils.R, R/visualize.R, R/wrappers.R, tests/testthat/test-calculate.R, tests/testthat/test-conf_int.R, tests/testthat/test-generate.R, tests/testthat/test-hypothesize.R, tests/testthat/test-p_value.R, tests/testthat/test-print.R, tests/testthat/test-rep_sample_n.R, tests/testthat/test-specify.R, tests/testthat/test-utils.R, tests/testthat/test-visualize.R, tests/testthat/test-wrappers.R
This a PR for #169. I ended up using some of {styler} functionality in the beginning to handle space issues. Everything else was done manually.
=> Update code style (#169)

DESCRIPTION
=> Added middle initial to "Albert Y. Kim"

DESCRIPTION
No biggie, but just wanted to correct spelling of my last name.
=> Correct spelling of PirateGrunt's last name

README.md
=> rendered README

R/calculate.R, R/generate.R, R/get_p_value.R, R/hypothesize.R, R/utils.R, R/visualize.R, tests/figs/visualize/ci-vis.svg, tests/figs/visualize/vis-no-hypothesize-both.svg, tests/figs/visualize/vis-no-hypothesize-sim.svg, tests/testthat/test-generate.R, tests/testthat/test-hypothesize.R, tests/testthat/test-visualize.R
This PR closes #253. It also clarifies error when permutation generation is attempted without hypothesis.
=> Make title of `visualize()` adapt to not hypothesis test framework

R/get_p_value.R, man/get_p_value.Rd, tests/testthat/test-get_p_value.R
=> Address zero output of `get_p_value()`

R/calculate.R, R/utils.R, R/wrappers.R, tests/testthat.R, tests/testthat/test-calculate.R, tests/testthat/test-wrappers.R
Some edits to address #275 -- I've written a bit more about what I changed on the issue!
=> specifying order in difference-based tests (#275)

R/calculate.R
A quick PR to fix an issue with `calculate`ing difference-based statistics--I've written some more notes on #291 !
=> fix grouping in diff-based calc_impl

NEWS.md, R/calculate.R, R/get_p_value.R, R/utils.R, R/visualize.R, man/calculate.Rd, tests/testthat/test-get_p_value.R, tests/testthat/test-utils.R, tests/testthat/test-visualize.R
Some changes to better handle NaNs resulting from #292 after `calculate`ing--more discussion there!
=> better handling of NaNs after calculate

.github/workflows/check-standard.yaml, NEWS.md, R/get_p_value.R, R/shade_p_value.R, R/utils.R, R/visualize.R, R/wrappers.R, man/get_p_value.Rd, man/prop_test.Rd, man/shade_p_value.Rd, man/t_stat.Rd, man/t_test.Rd, man/visualize.Rd, tests/testthat/test-get_p_value.R, tests/testthat/test-shade_p_value.R, vignettes/infer.Rmd, vignettes/observed_stat_examples.Rmd, vignettes/t_test.Rmd
=> add aliases for "two_sided" (#302)

CONDUCT.md, README.Rmd, README.md
Some small edits to use the newer version of the contributor covenant and link to tidymodels resources in the README!
=> update CoC, links to tidymodels resources

R/rep_sample_n.R, man/rep_sample_n.Rd
This is based off the `rep-sample-n` branch in PR #325 which fixes #279
=> Added weighted sampling example to rep_sample_n()

R/calculate.R, R/infer.R, man/calculate.Rd, man/infer.Rd, tests/testthat/test-calculate.R
This fixes #332 and refactors `calc_impl.Chisq()` (in particular to not use `dplyr::do()`).
=> Update `calculate(stat = "Chisq")`

R/gss.R, man/gss.Rd
=> mention range of years in gss documentation

.github/workflows/check-standard.yaml, CONTRIBUTING.md, R/calculate.R, R/generate.R, R/get_confidence_interval.R, R/get_p_value.R, R/hypothesize.R, R/observe.R, R/shade_confidence_interval.R, R/shade_p_value.R, R/specify.R, R/visualize.R, R/wrappers.R, _pkgdown.yml, man/calculate.Rd, man/chisq_stat.Rd, man/chisq_test.Rd, man/generate.Rd, man/get_confidence_interval.Rd, man/get_p_value.Rd, man/hypothesize.Rd, man/observe.Rd, man/prop_test.Rd, man/shade_confidence_interval.Rd, man/shade_p_value.Rd, man/specify.Rd, man/t_stat.Rd, man/t_test.Rd, man/visualize.Rd
Adds a few function `@family`s and `@seealso` tags so that help-files link to related help-files. :-)
=> link throughout documentation

vignettes/anova.Rmd, vignettes/chi_squared.Rmd, vignettes/t_test.Rmd
Mostly, this PR adds some qualifiers and clarification on what is an approximation of a distribution via randomization vs what is the theory-based distribution. Also, demonstrates usage of `p*` functions, transitions to untheorized statistics for demonstrating randomization-based tests, does some spellchecking, uses consistent notation for statistics. :-)
=> workshop test-specific vignettes

R/get_p_value.R, R/utils.R, tests/testthat/test-get_p_value.R
Closes #393!
Not feeling super confident on whether this prompt should be an error or a warning nor the wording of the prompt generally--open to suggestions. :-)
=> check for switched `x` and `obs_stat`

README.Rmd, README.md
Adding links to two books that discuss randomization-based statistical inference more thoroughly than our documentation/vignettes.
Not sure if the link to IMS is the preferred one, cc @mine-cetinkaya-rundel!
=> link out to ModernDive and IMS

.github/workflows/check-hard.yaml, .github/workflows/check-standard.yaml, .github/workflows/pkgdown.yaml, .gitignore, DESCRIPTION, README.Rmd, README.md, _pkgdown.yml, cran-comments.md, vignettes/anova.Rmd, vignettes/chi_squared.Rmd, vignettes/infer.Rmd, vignettes/observed_stat_examples.Rmd, vignettes/t_test.Rmd
=> troubleshoot Actions + spring cleaning

NEWS.md, R/infer.R, R/utils.R, tests/testthat/test-utils.R, tests/testthat/test-wrappers.R
=> set levels on `logical` -> `factor` conversion

R/utils.R
=> address `across` deprecation warning

NEWS.md, R/generate.R, R/hypothesize.R, R/utils.R, _pkgdown.yml, man/hypothesize.Rd, man/observe.Rd, tests/testthat/_snaps/generate.md, tests/testthat/_snaps/hypothesize.md, tests/testthat/test-hypothesize.R, vignettes/observed_stat_examples.Rmd, vignettes/paired.Rmd, vignettes/t_test.Rmd
Closes #487. Sitting tight on testing and proper docs until we know this is the direction we want to go!
=> add support for permutation test for paired data

NEWS.md, R/wrappers.R, man/prop_test.Rd, tests/testthat/_snaps/wrappers.md, tests/testthat/test-wrappers.R
Closes #496. See that issue for discussion. :)
=> fix bug in `prop.test()` wrapper

tests/testthat/_snaps/visualize/viz-fit-bare.svg, tests/testthat/_snaps/visualize/viz-fit-conf-int.svg, tests/testthat/_snaps/visualize/viz-fit-no-h0.svg, tests/testthat/_snaps/visualize/viz-fit-p-val-both.svg, tests/testthat/_snaps/visualize/viz-fit-p-val-left.svg, tests/testthat/_snaps/visualize/viz-fit-p-val-right.svg
Seeing new failures on `main`. I'm unable to tell the difference between the new and old.
=> update `visualize()` doppelgangers

DESCRIPTION, NEWS.md, R/deprecated.R, R/shade_confidence_interval.R, R/shade_p_value.R, R/wrappers.R, README.Rmd, README.md, cran-comments.md, man/deprecated.Rd, man/infer.Rd, man/shade_confidence_interval.Rd, man/shade_p_value.Rd, man/t_stat.Rd
cloud job ID "cc2a65d0-4139-4179-9265-880fc125e7bd"
=> v1.0.6 release candidate

NEWS.md, README.Rmd, vignettes/anova.Rmd, vignettes/chi_squared.Rmd, vignettes/infer.Rmd, vignettes/observed_stat_examples.Rmd, vignettes/paired.Rmd, vignettes/t_test.Rmd
Added missing commas and formatting issues throughout the vignettes. Backticks for package names were removed, and missing parentheses for functions were added.
=> Modify vignettes and articles to match tidy formatting

DESCRIPTION, NEWS.md, cran-comments.md
Closes #551.
Cloud check ID `"e0a73338-8996-4236-8587-a0b2842e3f29"`.
=> v1.0.8 release candidate

DESCRIPTION, NEWS.md, cran-comments.md
Cloud check id is `"3e3f96e8-66bb-464d-b830-4dbfc9f6029d"`.
Win-devel: 
> Check <simon.couch@posit.co> for the results in 15-30 mins (~12:42 PM).
=> release candidate 1.0.9
